apiVersion: v1
kind: Service
metadata:
  name: currentweather
  labels:
    app: currentweather
spec:
  ports:
    - port: 80
      targetPort: cw-server
  selector:
    app: currentweather
  type: NodePort # LoadBalancer | NodePort