apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: redis
#  type: NodePort # LoadBalancer | NodePort